### ISSUE TITLE
ini save path triggers "Unexpected files found" message from Rockstar Launcher

### ISSUE THREAD

**Issue by Zazama** [QuickNET-Tech/GTAO_Booster_PoC#3]
Hey,
first of all, thanks for your addition to tostercx's amazing work!

When using your provided .dll v1.0.2+, it seems that Rockstar Launcher detects the .ini in the install directory, opening a window before starting the game stating that unexpected files were found and can result in a permanent ban.
Now, I don't think you'll get banned for the ini, but players without that much technical knowledge might be scared.
Also, at first, I didn't even know that the configuration ini is at fault.

Because of that, it might be a good idea to create the configuration file in the path where the .dll is already in.
What do you think about that?

**Comment by ridetheflatline** [comment]
imho better off not adding any extra file into GTA install path... the file only holds 1 variable for console on/off

**Comment by QuickNET-Tech** [comment]
It's a scare message that doesn't have any real effect. At this time I don't have any real plans to change it, but if more people want it changed then It's certainly something I would consider.

**Comment by QuickNET-Tech** [comment]
Ini will be dropped as R* fixed the online load times so this will no longer be a concern. This mod will be made to just skip logos/legals to speed up single player load times.
