### ISSUE TITLE
[Suggestion] Patching the EXE instead of injecting a DLL every time.

### ISSUE THREAD

**Issue by Aholicknight** [QuickNET-Tech/GTAO_Booster_PoC#5]
![image](https://user-images.githubusercontent.com/7843719/111039605-7f8ae500-83f4-11eb-9522-5a4ec6779720.png)
A lot of patchers exist like dUP2 + AT4RE to patch the exe or a DLL. Is there a way that we can do this so we don't have to inject a DLL every time?

**Comment by QuickNET-Tech** [comment]
Patching the EXE should certainly be possible, though more difficult as it's more protected when not running, but I'd rather not making changes to the EXE itself. The nice thing about the DLL is it's changes are temporary, which was the point.

**Comment by Aholicknight** [comment]
How would it be possible? Could you make a patched exe then I can create the patcher using dUP2 or AT4RE? Maybe some users are looking for a permanent change instead of injecting the DLL every time they want to play GTA.

**Comment by QuickNET-Tech** [comment]
> How would it be possible?

There's many ways, manual hex editing and writing a program to read the file in as a binary file, make edits and write it back out are the two that come to mind.

> Could you make a patched exe then I can create the patcher using dUP2 or AT4RE?

I'm probably capable.

> Maybe some users are looking for a permanent change instead of injecting the DLL every time they want to play GTA.

That's not something I'm interested in making, if someone wants that the source is open and people are free to use it to make such a thing if they wish.

**Comment by Aholicknight** [comment]
> > How would it be possible?
> 
> There's many ways, manual hex editing and writing a program to read the file in as a binary file, make edits and write it back out are the two that come to mind.
> 
> > Could you make a patched exe then I can create the patcher using dUP2 or AT4RE?
> 
> I'm probably capable.
> 
> > Maybe some users are looking for a permanent change instead of injecting the DLL every time they want to play GTA.
> 
> That's not something I'm interested in making, if someone wants that the source is open and people are free to use it to make such a thing if they wish.

That's great you can do it, I would do it myself but I do not know how to create the patched exe. I can do everything else fine (creating the patcher, etc) but creating the patched exe would be the hard part.
