### ISSUE TITLE
Windows Defender Virus warning - Trojan:Win32/Spursint.Q!cl

### ISSUE THREAD

**Issue by pcislocked** [QuickNET-Tech/GTAO_Booster_PoC#7]
![hobb ss aldim 084](https://user-images.githubusercontent.com/50513999/111082095-88c0a280-8517-11eb-80a4-ddc11fb28093.jpg)

It is false positive... I guess... It didn't give the warning when I downloaded it when it was released, (I also did a full scan two days ago, no alerts) So the virus definition is surely new.

**Comment by QuickNET-Tech** [comment]
I'm sorry there's not much I can do about it.
See: https://github.com/QuickNET-Tech/Universal_GTAO_Booster#anti-virus
