### ISSUE TITLE
Pattern 'netCatalogueInsertUnique' failed.

### ISSUE THREAD

**Issue by d0t-d0t-d0t** [QuickNET-Tech/GTAO_Booster_PoC#8]
when i inject the dll it shows me this message:
Pattern 'netCatalogueInsertUnique' failed.

**Comment by Raphitpt** [comment]
Yes, same for me

**Comment by ASHBLY33** [comment]
Same for me "Pattern 'netCatalogueInsertUnique' failed."
also i tried restarting GTA but nothing

**Comment by lvck1** [comment]
Because R* has fixed this bug, we no longer need to use this dll. Thank you for the author’s contribution.

**Comment by QuickNET-Tech** [comment]
This mod will no longer be needed for online speedup. It will soon be made to only speed up single player load times.
