### ISSUE TITLE
Bump minhook dep 

### ISSUE THREAD

**Issue by WSLUser** [QuickNET-Tech/GTAO_Booster_PoC#9]
There's an updated commit from this year and have a few others that allow support for cmake and VS 2019: https://github.com/TsudaKageyu/minhook/commit/423d1e45af2ed2719a5c31e990e935ef301ed9c3. Please bump to this commit.

**Comment by QuickNET-Tech** [comment]
No idea about cmake but I'm building this with VS 2019.
Either way, minhook is being dropped because there will be no reason to keep it here soon. The only things that were being hooked are now patched by R*.
